# Generated by Django 4.1.1 on 2022-09-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prise',
            field=models.FloatField(),
        ),
    ]
