# Generated by Django 4.1.1 on 2022-09-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_app', '0002_alter_item_prise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание и характеристики товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='prise',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
