# Generated by Django 4.1.1 on 2022-09-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_app', '0004_alter_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='prise',
            new_name='price',
        ),
    ]
